#!/bin/bash
export PATH="/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/bin:/run/current-system/sw/bin:$PATH"

export TERM="${TERM:-xterm-256color}"
exec </dev/tty >/dev/tty
projects_dir="/Users/thalesgelinger/Projects"
if [ -n "$TMUX_POPUP" ]; then
    selected=$(find "$projects_dir" -mindepth 1 -maxdepth 2 -type d | fzf --delimiter=Projects/ --with-nth=2.. --reverse --height 100% --layout=reverse --border)
else
    selected=$(find "$projects_dir" -mindepth 1 -maxdepth 2 -type d | fzf-tmux --delimiter=Projects/ --with-nth=2.. --reverse -h)
fi
[[ -z $selected ]] && exit 0
selected_name=$(basename "$selected" | tr . _)
if ! tmux has-session -t=$selected_name 2>/dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi
tmux switch-client -t $selected_name
